export enum MarketType {
  ONE_X_TWO = "1X2",
  DOUBLE_CHANCE = "double_chance",
  OVER_UNDER = "over_under",
  OVER_UNDER_FIRST_HALF = "over_under_first_half",
  OVER_UNDER_SECOND_HALF = "over_under_second_half",
  HANDICAP = "handicap",
  HANDICAP_FIRST_HALF = "handicap_first_half",
  HANDICAP_SECOND_HALF = "handicap_second_half",
  BTTS = "btts",
  BTTS_FIRST_HALF = "btts_first_half",
  BTTS_SECOND_HALF = "btts_second_half",
  EXACT_SCORE = "exact_score",
  CORRECT_SCORE = "correct_score",
  HALF_TIME = "half_time",
  FULL_TIME = "full_time",
  HALF_TIME_FULL_TIME = "half_time_full_time",
  TOTAL_CORNERS = "total_corners",
  TOTAL_CORNERS_FIRST_HALF = "total_corners_first_half",
  TOTAL_CORNERS_SECOND_HALF = "total_corners_second_half",
  TOTAL_CARDS = "total_cards",
  TOTAL_CARDS_FIRST_HALF = "total_cards_first_half",
  TOTAL_YELLOW_CARDS = "total_yellow_cards",
  TOTAL_RED_CARDS = "total_red_cards",
  PLAYER_TO_SCORE = "player_to_score",
  PLAYER_TO_SCORE_ANYTIME = "player_to_score_anytime",
  PLAYER_TO_SCORE_FIRST = "player_to_score_first",
  TOTAL_GOALS = "total_goals",
  TOTAL_GOALS_FIRST_HALF = "total_goals_first_half",
  TOTAL_GOALS_SECOND_HALF = "total_goals_second_half",
  BOTH_HALVES_OVER = "both_halves_over",
  RACE_TO_GOALS = "race_to_goals",
  DRAW_NO_BET = "draw_no_bet",
  WIN_BOTH_HALVES = "win_both_halves",
  CLEAN_SHEET = "clean_sheet",
  SCORE_CAST = "score_cast",
  GOALS_ODD_EVEN = "goals_odd_even",
  PENALTY_SHOOTOUT_WINNER = "penalty_shootout_winner",
  EXTRA_TIME_WINNER = "extra_time_winner",
  CORNER_RACE = "corner_race",
  CARD_RACE = "card_race",
}

export interface MarketDefinition {
  type: MarketType;
  name: string;
  nameFr: string;
  hasHandicap: boolean;
  hasOverUnder: boolean;
  isHalfTimeRelated: boolean;
  isPlayerRelated: boolean;
}

export const MARKET_DEFINITIONS: Record<MarketType, MarketDefinition> = {
  [MarketType.ONE_X_TWO]: { type: MarketType.ONE_X_TWO, name: "1X2", nameFr: "1N2", hasHandicap: false, hasOverUnder: false, isHalfTimeRelated: false, isPlayerRelated: false },
  [MarketType.DOUBLE_CHANCE]: { type: MarketType.DOUBLE_CHANCE, name: "Double Chance", nameFr: "Double Chance", hasHandicap: false, hasOverUnder: false, isHalfTimeRelated: false, isPlayerRelated: false },
  [MarketType.OVER_UNDER]: { type: MarketType.OVER_UNDER, name: "Over/Under", nameFr: "Plus/Moins", hasHandicap: false, hasOverUnder: true, isHalfTimeRelated: false, isPlayerRelated: false },
  [MarketType.HANDICAP]: { type: MarketType.HANDICAP, name: "Handicap", nameFr: "Handicap", hasHandicap: true, hasOverUnder: false, isHalfTimeRelated: false, isPlayerRelated: false },
  [MarketType.BTTS]: { type: MarketType.BTTS, name: "Both Teams to Score", nameFr: "Les deux marquent", hasHandicap: false, hasOverUnder: false, isHalfTimeRelated: false, isPlayerRelated: false },
  [MarketType.EXACT_SCORE]: { type: MarketType.EXACT_SCORE, name: "Exact Score", nameFr: "Score Exact", hasHandicap: false, hasOverUnder: false, isHalfTimeRelated: false, isPlayerRelated: false },
  [MarketType.HALF_TIME]: { type: MarketType.HALF_TIME, name: "Half Time", nameFr: "Mi-temps", hasHandicap: false, hasOverUnder: false, isHalfTimeRelated: false, isPlayerRelated: false },
  [MarketType.TOTAL_CORNERS]: { type: MarketType.TOTAL_CORNERS, name: "Total Corners", nameFr: "Nombre de corners", hasHandicap: false, hasOverUnder: true, isHalfTimeRelated: false, isPlayerRelated: false },
  [MarketType.TOTAL_CARDS]: { type: MarketType.TOTAL_CARDS, name: "Total Cards", nameFr: "Nombre de cartons", hasHandicap: false, hasOverUnder: true, isHalfTimeRelated: false, isPlayerRelated: false },
  [MarketType.PLAYER_TO_SCORE]: { type: MarketType.PLAYER_TO_SCORE, name: "Player to Score", nameFr: "Joueur marque", hasHandicap: false, hasOverUnder: false, isHalfTimeRelated: false, isPlayerRelated: true },
  [MarketType.DRAW_NO_BET]: { type: MarketType.DRAW_NO_BET, name: "Draw No Bet", nameFr: "Nul remboursé", hasHandicap: false, hasOverUnder: false, isHalfTimeRelated: false, isPlayerRelated: false },
  [MarketType.GOALS_ODD_EVEN]: { type: MarketType.GOALS_ODD_EVEN, name: "Goals Odd/Even", nameFr: "Buts Pair/Impair", hasHandicap: false, hasOverUnder: false, isHalfTimeRelated: false, isPlayerRelated: false },
  [MarketType.OVER_UNDER_FIRST_HALF]: { type: MarketType.OVER_UNDER_FIRST_HALF, name: "O/U 1st Half", nameFr: "P/M 1ère MT", hasHandicap: false, hasOverUnder: true, isHalfTimeRelated: true, isPlayerRelated: false },
  [MarketType.OVER_UNDER_SECOND_HALF]: { type: MarketType.OVER_UNDER_SECOND_HALF, name: "O/U 2nd Half", nameFr: "P/M 2ème MT", hasHandicap: false, hasOverUnder: true, isHalfTimeRelated: true, isPlayerRelated: false },
  [MarketType.HANDICAP_FIRST_HALF]: { type: MarketType.HANDICAP_FIRST_HALF, name: "Handicap 1st Half", nameFr: "Handicap 1ère MT", hasHandicap: true, hasOverUnder: false, isHalfTimeRelated: true, isPlayerRelated: false },
  [MarketType.HANDICAP_SECOND_HALF]: { type: MarketType.HANDICAP_SECOND_HALF, name: "Handicap 2nd Half", nameFr: "Handicap 2ème MT", hasHandicap: true, hasOverUnder: false, isHalfTimeRelated: true, isPlayerRelated: false },
  [MarketType.BTTS_FIRST_HALF]: { type: MarketType.BTTS_FIRST_HALF, name: "BTTS 1st Half", nameFr: "Les deux marquent 1MT", hasHandicap: false, hasOverUnder: false, isHalfTimeRelated: true, isPlayerRelated: false },
  [MarketType.BTTS_SECOND_HALF]: { type: MarketType.BTTS_SECOND_HALF, name: "BTTS 2nd Half", nameFr: "Les deux marquent 2MT", hasHandicap: false, hasOverUnder: false, isHalfTimeRelated: true, isPlayerRelated: false },
  [MarketType.HALF_TIME_FULL_TIME]: { type: MarketType.HALF_TIME_FULL_TIME, name: "HT/FT", nameFr: "MT/FT", hasHandicap: false, hasOverUnder: false, isHalfTimeRelated: true, isPlayerRelated: false },
  [MarketType.TOTAL_CORNERS_FIRST_HALF]: { type: MarketType.TOTAL_CORNERS_FIRST_HALF, name: "Corners 1st Half", nameFr: "Corners 1MT", hasHandicap: false, hasOverUnder: true, isHalfTimeRelated: true, isPlayerRelated: false },
  [MarketType.TOTAL_CORNERS_SECOND_HALF]: { type: MarketType.TOTAL_CORNERS_SECOND_HALF, name: "Corners 2nd Half", nameFr: "Corners 2MT", hasHandicap: false, hasOverUnder: true, isHalfTimeRelated: true, isPlayerRelated: false },
  [MarketType.TOTAL_CARDS_FIRST_HALF]: { type: MarketType.TOTAL_CARDS_FIRST_HALF, name: "Cards 1st Half", nameFr: "Cartons 1MT", hasHandicap: false, hasOverUnder: true, isHalfTimeRelated: true, isPlayerRelated: false },
  [MarketType.RACE_TO_GOALS]: { type: MarketType.RACE_TO_GOALS, name: "Race to Goals", nameFr: "Course aux buts", hasHandicap: false, hasOverUnder: false, isHalfTimeRelated: false, isPlayerRelated: false },
  [MarketType.CLEAN_SHEET]: { type: MarketType.CLEAN_SHEET, name: "Clean Sheet", nameFr: "Clean sheet", hasHandicap: false, hasOverUnder: false, isHalfTimeRelated: false, isPlayerRelated: false },
  [MarketType.SCORE_CAST]: { type: MarketType.SCORE_CAST, name: "Score Cast", nameFr: "Score exact + buteur", hasHandicap: false, hasOverUnder: false, isHalfTimeRelated: false, isPlayerRelated: true },
  [MarketType.PENALTY_SHOOTOUT_WINNER]: { type: MarketType.PENALTY_SHOOTOUT_WINNER, name: "Penalty Winner", nameFr: "Gagnant tirs au but", hasHandicap: false, hasOverUnder: false, isHalfTimeRelated: false, isPlayerRelated: false },
  [MarketType.CORNER_RACE]: { type: MarketType.CORNER_RACE, name: "Corner Race", nameFr: "Course aux corners", hasHandicap: false, hasOverUnder: false, isHalfTimeRelated: false, isPlayerRelated: false },
  [MarketType.CARD_RACE]: { type: MarketType.CARD_RACE, name: "Card Race", nameFr: "Course aux cartons", hasHandicap: false, hasOverUnder: false, isHalfTimeRelated: false, isPlayerRelated: false },
  [MarketType.TOTAL_GOALS]: { type: MarketType.TOTAL_GOALS, name: "Total Goals", nameFr: "Total buts", hasHandicap: false, hasOverUnder: true, isHalfTimeRelated: false, isPlayerRelated: false },
  [MarketType.TOTAL_GOALS_FIRST_HALF]: { type: MarketType.TOTAL_GOALS_FIRST_HALF, name: "Goals 1st Half", nameFr: "Buts 1MT", hasHandicap: false, hasOverUnder: true, isHalfTimeRelated: true, isPlayerRelated: false },
  [MarketType.TOTAL_GOALS_SECOND_HALF]: { type: MarketType.TOTAL_GOALS_SECOND_HALF, name: "Goals 2nd Half", nameFr: "Buts 2MT", hasHandicap: false, hasOverUnder: true, isHalfTimeRelated: true, isPlayerRelated: false },
  [MarketType.PLAYER_TO_SCORE_ANYTIME]: { type: MarketType.PLAYER_TO_SCORE_ANYTIME, name: "Anytime Scorer", nameFr: "Buteur", hasHandicap: false, hasOverUnder: false, isHalfTimeRelated: false, isPlayerRelated: true },
  [MarketType.PLAYER_TO_SCORE_FIRST]: { type: MarketType.PLAYER_TO_SCORE_FIRST, name: "First Scorer", nameFr: "Premier buteur", hasHandicap: false, hasOverUnder: false, isHalfTimeRelated: false, isPlayerRelated: true },
  [MarketType.BOTH_HALVES_OVER]: { type: MarketType.BOTH_HALVES_OVER, name: "Both Halves Over", nameFr: "Les 2 MT + de 0.5", hasHandicap: false, hasOverUnder: true, isHalfTimeRelated: true, isPlayerRelated: false },
  [MarketType.WIN_BOTH_HALVES]: { type: MarketType.WIN_BOTH_HALVES, name: "Win Both Halves", nameFr: "Gagne les 2 MT", hasHandicap: false, hasOverUnder: false, isHalfTimeRelated: true, isPlayerRelated: false },
  [MarketType.CORRECT_SCORE]: { type: MarketType.CORRECT_SCORE, name: "Correct Score", nameFr: "Score Exact", hasHandicap: false, hasOverUnder: false, isHalfTimeRelated: false, isPlayerRelated: false },
  [MarketType.FULL_TIME]: { type: MarketType.FULL_TIME, name: "Full Time", nameFr: "Temps réglementaire", hasHandicap: false, hasOverUnder: false, isHalfTimeRelated: false, isPlayerRelated: false },
  [MarketType.EXTRA_TIME_WINNER]: { type: MarketType.EXTRA_TIME_WINNER, name: "Extra Time Winner", nameFr: "Gagnant prolongation", hasHandicap: false, hasOverUnder: false, isHalfTimeRelated: false, isPlayerRelated: false },
  [MarketType.TOTAL_YELLOW_CARDS]: { type: MarketType.TOTAL_YELLOW_CARDS, name: "Yellow Cards", nameFr: "Cartons jaunes", hasHandicap: false, hasOverUnder: true, isHalfTimeRelated: false, isPlayerRelated: false },
  [MarketType.TOTAL_RED_CARDS]: { type: MarketType.TOTAL_RED_CARDS, name: "Red Cards", nameFr: "Cartons rouges", hasHandicap: false, hasOverUnder: true, isHalfTimeRelated: false, isPlayerRelated: false },
};
